services:
  web:
    build: .
    env_file: .env
    environment:
      - POSTGRES_DB=ohte
      - TEST_POSTGRES_DB=test_ohte
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=unsecure
      - POSTGRES_HOST

      - POSTGRES_URL
      - TEST_POSTGRES_URL
      - ENV
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=ohte
      - POSTGRES_USER=ohte
      - POSTGRES_PASSWORD=unsecure
      - POSTGRES_HOST
      - POSTGER_INITDB_ARGS="-c listen_addresses = '*'"
    volumes:
      # - ./docker/schema.sql:/docker-entrypoint-initdb.d/initdb.sql
      - pgdata:/var/lib/postgresql/data

    networks:
      - backend
    healthcheck:
      test: sh -c "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
      interval: 3s
      timeout: 2s
      retries: 30
      # expose:
      # - 5432
      # ports:
      # - "5432:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:

networks:
  backend:
