[tool.poetry]
name = "ohte"
version = "0.1.0"
description = ""
authors = ["iritmaximus <aaro.koivukangas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
pylint = "^2.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
