name: GH actions test/lint
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v3

      - name: Run image
        uses: abatilo/actions-poetry@v2

      - name: Install packages
        run: poetry install


  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Run image
        uses: abatilo/actions-poetry@v2

      - name: Run pylint
        run: poetry run pylint src

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Run image
        uses: abatilo/actions-poetry@v2

      - name: Run tests
        run: poetry run pytest src
